package com.example.demo.model.enums;

public enum Motives {
    PIZZA,
    BURGER,
    SUSHI,
    KEBAB,
    KUCHNIA_POLSKA,
    KUCHNIA_MEKSYKANSKA,
    KUCHNIA_AMERYKANSKA,
    KUCHNIA_WLOSKA,
    KUCHNIA_CHINSKA,
    KUCHNIA_TURECKA,
    KUCHNIA_INDYJSKA,
    KUCHNIA_WIETNAMSKA,
    KUCHNIA_JAPONSKA,
    KUCHNIA_TAJSKA,
    KUCHNIA_WEGETARIANSKA,
    KUCHNIA_WEGANSKA,
    ZUPA,
    PIEROGI,
    SALATKA,
    KANAPKA,
    MAKARON,
    NALESNIKI

}
